apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170954806
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170954806
    app.kubernetes.io/part-of: test-app-170954806
  name: java-quarkus-170954806
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170954806
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170954806
    spec:
      containers:
      - image: quay.io/hacdev/1a86nqpk-tenant/test-app-170954806/java-quarkus-170954806@sha256:e3690d8b93954d9d0a56c31761d8292cdc8ac106d13118b364513a3ebe85b155
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
